package dev.casz.caszualmtg;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents;
import com.mojang.serialization.JsonOps;
import net.minecraft.resources.RegistryOps;
import com.spider.mtgcard.content.pack.cache.ScryfallModels;
import com.spider.mtgcard.util.*;
import com.spider.mtgcard.api.CardDatabaseCards;
import java.util.*;
public final class IntegrationChecks implements ModInitializer {
 static void check(boolean x,String m){if(!x)throw new AssertionError(m);}
 public void onInitialize(){ServerLifecycleEvents.SERVER_STARTED.register(server->{try{
  ScryfallModels.Card model=new ScryfallModels.Card();model.id="dcd97880-ded6-42d2-b2d9-9e6627e51041";model.oracleId=model.id;model.name="Integration Test Artifact";model.set="tst";model.collectorNumber="1";model.rarity="common";model.layout="normal";model.typeLine="Artifact";model.oracleText="";model.manaCost="{1}";model.colors=List.of();model.colorIdentity=List.of();model.legalities=Map.of("commander","legal");model.imageUris=Map.of();model.faces=List.of();
  var card=CardStackBuilders.buildScryfallStackFromModel(model,false);check(Banks.kind(card)==2,"metadata classification");Banks b=new Banks();b.add(card,2,4);b.add(card,2,2);String key=Banks.key(2,card);check(b.entries.get(key).count()==6,"community deposits counted");b.take(key,2);check(b.entries.get(key).count()==4,"withdrawal consumed stock");
  var ops=RegistryOps.create(JsonOps.INSTANCE,server.registryAccess());var encoded=Banks.CODEC.encodeStart(ops,b).getOrThrow();var decoded=Banks.CODEC.parse(ops,encoded).getOrThrow();check(decoded.entries.get(key).count()==4,"saved-data codec roundtrip");decoded.take(key,4);check(decoded.entries.isEmpty(),"stock exhaustion removes entry");
  model.typeLine="Basic Land — Forest";model.name="Integration Forest";model.id="3e76d43e-347c-4b68-ae11-3cac1a58440b";var land=CardStackBuilders.buildScryfallStackFromModel(model,false);check(Banks.kind(land)==0,"land classification");b.add(land,0,9999);String lk=Banks.key(0,land);check(b.entries.get(lk).count()==1,"unlimited catalogue stores template");b.take(lk,99);check(b.entries.containsKey(lk),"unlimited copies do not exhaust catalogue");
  model.typeLine="Token Creature — Soldier";model.isTokenLike=true;model.name="Integration Soldier";model.id="958b1a2c-919b-40a8-a1f6-d2e7e71e7e91";var token=CardStackBuilders.buildScryfallStackFromModel(model,false);check(Banks.kind(token)==1,"token classification");
  var one=CardDatabaseCards.copyForExtraction(card);var two=CardDatabaseCards.copyForExtraction(card);check(!StackData.readCustom(one).getString("mtg_uid").equals(StackData.readCustom(two).getString("mtg_uid")),"generated cards have distinct instance UIDs");CardCounterNbt.setCounter(one,"charge",7);check(CardCounterNbt.readCounterMap(one).get("charge")==7,"MTGCard counters compatible");CardCounterNbt.removeCounter(one,"charge");check(!CardCounterNbt.readCounterMap(one).containsKey("charge"),"counter removal compatible");Banks.get(server).setDirty();
  model.typeLine="Emblem — Test";model.name="Not a token";var emblem=CardStackBuilders.buildScryfallStackFromModel(model,false);check(Banks.kind(emblem)==2,"token-like emblems excluded");
  var player=new net.minecraft.server.level.ServerPlayer(server,server.overworld(),new com.mojang.authlib.GameProfile(UUID.randomUUID(),"TransferTest"),net.minecraft.server.level.ClientInformation.createDefault());
  var boxItem=net.minecraft.core.registries.BuiltInRegistries.ITEM.stream().filter(i->i instanceof com.spider.mtgcard.deckbox.DeckboxBlockItem).findFirst().orElseThrow();var box=new net.minecraft.world.item.ItemStack(boxItem);var items=net.minecraft.core.NonNullList.withSize(com.spider.mtgcard.deckbox.DeckboxBlockEntity.INVENTORY_SIZE,net.minecraft.world.item.ItemStack.EMPTY);items.set(0,card.copy());items.set(1,land.copy());items.set(99,token.copy());
  var loaded=new DeckboxTransfer.Loaded(UUID.randomUUID(),net.minecraft.core.registries.BuiltInRegistries.BLOCK.getKey(((com.spider.mtgcard.deckbox.DeckboxBlockItem)boxItem).getBlock()).toString(),"Test box",items);DeckboxTransfer.save(player,box,loaded);Banks transfer=new Banks();check(DeckboxTransfer.deposit(player,box,transfer)==1,"bulk regular-card deposit");var after=DeckboxTransfer.load(player,box);check(after.items().get(0).isEmpty()&&!after.items().get(1).isEmpty()&&!after.items().get(99).isEmpty(),"deposit preserves lands/tokens and special slot");check(DeckboxTransfer.withdraw(player,box,transfer,Banks.key(2,card),"",99)==1,"withdraw limited by actual shared stock");check(transfer.entries.isEmpty(),"bulk withdrawal consumes shared stock");check(!DeckboxTransfer.load(player,box).items().get(0).isEmpty(),"withdraw persisted box contents");
  check(DeckboxTransfer.deposit(player,box,transfer)==1,"repeat deposit");check(DeckboxTransfer.deposit(player,box,transfer)==0,"repeat action does not duplicate deposit");transfer.add(card,2,200);check(DeckboxTransfer.withdraw(player,box,transfer,null,"",99)==98,"fill respects 99 main slots and existing land");check(!DeckboxTransfer.load(player,box).items().get(99).isEmpty(),"withdraw leaves special token slot");
  var parsed=com.google.gson.JsonParser.parseString("{\"type_line\":\"Basic Land — Forest\",\"produced_mana\":[\"G\"],\"cmc\":0,\"name\":\"Forest\"}").getAsJsonObject();check(Catalogue.manaMask(parsed)==16,"produced mana mapping");Catalogue.setMana(land,16);Banks cached=new Banks();cached.add(land,0,1);check(Catalogue.matchesMana(cached.entries.values().iterator().next().card(),16),"bank preserves produced-mana metadata");check(Catalogue.matchesMana(land,16)&&!Catalogue.matchesMana(land,1),"cached mana filters");check(Catalogue.query(0,"Forest",16).contains("produces:G"),"mana API query");check(Catalogue.query(1,"Soldier",0).startsWith("t:token"),"strict token API query");
  var at=new net.minecraft.core.BlockPos(0,100,0);server.overworld().getChunkAt(at);server.overworld().setBlock(at,CaszualMtg.BUILDER.defaultBlockState(),3);server.overworld().setBlock(at.east(),CaszualMtg.CARDS.defaultBlockState(),3);server.overworld().setBlock(at.west(),CaszualMtg.LANDS.defaultBlockState(),3);Banks shared=Banks.get(server);shared.entries.clear();shared.add(card,2,4);shared.add(land,0,1);var session=new ServerLogic.Session(player,at,3);session.deck="6 Integration Test Artifact\n2 Integration Forest\n3 Missing Test Card";ServerLogic.plan(player,session,false,0);check(session.statuses.size()==3,"all imported cards remain visible");check(session.statuses.get(0).count()==4&&session.statuses.get(0).requested()==6,"partial stock status");check(session.statuses.get(1).count()==2,"unlimited land status");check(session.statuses.get(2).count()==0&&session.statuses.get(2).card().isEmpty(),"missing card visible without stack");check(session.report.contains("2 Integration Test Artifact")&&session.report.contains("3 Missing Test Card"),"shopping list includes only missing quantities");
  var customAt=at.above(3);var customState=CaszualMtg.CUSTOM_BOX.defaultBlockState();server.overworld().setBlock(customAt,customState,3);var custom=(com.spider.mtgcard.deckbox.DeckboxBlockEntity)server.overworld().getBlockEntity(customAt);check(custom.getType().isValid(customState),"custom deckbox accepted by native entity type");var customItem=new net.minecraft.world.item.ItemStack(CaszualMtg.CUSTOM_BOX);customItem.set(CaszualMtg.BOX_MATERIAL,"minecraft:diamond_block");CaszualMtg.CUSTOM_BOX.setPlacedBy(server.overworld(),customAt,customState,player,customItem);check(((BoxMaterial)custom).companion$material().equals("minecraft:diamond_block"),"placed item material applied");custom.setStack(0,card.copy());custom.persistExternalRecord();var customId=custom.getStorageId();player.setShiftKeyDown(true);var gold=new net.minecraft.world.item.ItemStack(net.minecraft.world.item.Items.GOLD_BLOCK,2);CaszualMtg.CUSTOM_BOX.useItemOn(gold,customState,server.overworld(),customAt,player,net.minecraft.world.InteractionHand.MAIN_HAND,new net.minecraft.world.phys.BlockHitResult(net.minecraft.world.phys.Vec3.atCenterOf(customAt),net.minecraft.core.Direction.NORTH,customAt,false));check(gold.getCount()==1&&((BoxMaterial)custom).companion$material().equals("minecraft:gold_block"),"texture application consumes one source block");check(!custom.getStack(0).isEmpty()&&customId.equals(custom.getStorageId()),"retexture preserves deck contents and storage identity");player.setShiftKeyDown(false);
  var customDrops=net.minecraft.world.level.block.Block.getDrops(customState,server.overworld(),customAt,custom,player,net.minecraft.world.item.ItemStack.EMPTY);check(customDrops.size()==1,"single custom deckbox loot");var customDrop=customDrops.getFirst();check(customDrop.is(CaszualMtg.CUSTOM_BOX.asItem())&&customDrop.get(CaszualMtg.BOX_MATERIAL).equals("minecraft:gold_block"),"loot preserves material component");check(StackData.readCustom(customDrop).getString("mtgcard_deckbox_id").orElse("").equals(customId.toString()),"loot preserves card storage identity");check(custom.getUpdateTag(server.registryAccess()).getString("CompanionMaterial").orElse("").equals("minecraft:gold_block"),"material synchronized to clients");check(custom.getRenderData().equals("minecraft:gold_block"),"thread-safe renderer material snapshot");
  server.overworld().setBlock(customAt,net.minecraft.world.level.block.Blocks.AIR.defaultBlockState(),3);server.overworld().setBlock(customAt,customState,3);CaszualMtg.CUSTOM_BOX.setPlacedBy(server.overworld(),customAt,customState,player,customDrop);var replaced=(com.spider.mtgcard.deckbox.DeckboxBlockEntity)server.overworld().getBlockEntity(customAt);check(((BoxMaterial)replaced).companion$material().equals("minecraft:gold_block")&&!replaced.getStack(0).isEmpty(),"pickup and placement retain texture and contents");check(BoxMaterial.safe("minecraft:air").equals(BoxMaterial.DEFAULT),"invalid material fallback");
  model.typeLine="Basic Land — Test";model.isTokenLike=false;model.legalities=Map.of("commander","legal");model.colorIdentity=List.of("W","G");var dual=CardStackBuilders.buildScryfallStackFromModel(model,false);Catalogue.metadata(dual,model,17,false);check(!Catalogue.matchesMana(dual,16)&&Catalogue.matchesMana(dual,17),"green-white land requires both selected colors");model.colorIdentity=List.of("G");var greenWithWhiteAbility=CardStackBuilders.buildScryfallStackFromModel(model,false);Catalogue.metadata(greenWithWhiteAbility,model,17,false);check(!Catalogue.matchesMana(greenWithWhiteAbility,16),"unselected mana production excluded independently of identity");model.legalities=Map.of("commander","banned");var banned=CardStackBuilders.buildScryfallStackFromModel(model,false);Catalogue.metadata(banned,model,16,false);check(!Catalogue.matchesMana(banned,0),"banned land excluded even in All");
  model.typeLine="Token Creature — Soldier";model.name="Soldier";model.power="1";model.toughness="1";model.oracleText="Flying";model.isTokenLike=true;model.oracleId="12345678-1234-1234-1234-123456789abc";var filteredToken=CardStackBuilders.buildScryfallStackFromModel(model,false);Catalogue.metadata(filteredToken,model,0,false);check(Catalogue.matchesToken(filteredToken,"flying","1/1"),"optional token filters combine");check(!Catalogue.matchesToken(filteredToken,"vigilance","1/1")&&!Catalogue.matchesToken(filteredToken,"flying","2/2"),"token oracle and stats mismatches excluded");check(Catalogue.matchesToken(filteredToken,"",""),"blank token fields impose no filter");check(Catalogue.artworkQuery(1,filteredToken).contains("oracleid:"+model.oracleId),"art picker restricted to selected token rules identity");Banks artworkBank=new Banks();artworkBank.add(filteredToken,1,1);check(Catalogue.artworkQuery(1,artworkBank.entries.values().iterator().next().card()).contains(model.oracleId),"art identity survives bank template copy");
  var buf=new net.minecraft.network.RegistryFriendlyByteBuf(io.netty.buffer.Unpooled.buffer(),server.registryAccess());var reply=new Wire.Reply(net.minecraft.core.BlockPos.ZERO,3,"Loaded","1 Missing",List.of(new Wire.Row("Missing",net.minecraft.world.item.ItemStack.EMPTY,0,1)));var request=new Wire.Request(net.minecraft.core.BlockPos.ZERO,"search","Soldier",0,0,"Flying","1/1");Wire.Request.CODEC.encode(buf,request);var decodedRequest=Wire.Request.CODEC.decode(buf);check(decodedRequest.oracle().equals("Flying")&&decodedRequest.stats().equals("1/1"),"optional token search fields network roundtrip");Wire.Reply.CODEC.encode(buf,reply);var decodedReply=Wire.Reply.CODEC.decode(buf);check(decodedReply.rows().getFirst().card().isEmpty()&&decodedReply.rows().getFirst().requested()==1,"missing-card statuses network roundtrip");buf.release();

  System.out.println("MTGCOMPANION_INTEGRATION_PASS: storage, codec, strict types, mana filters, finite bulk deckbox transfers, missing-card status networking, unique UIDs, counters, custom deckbox material/loot/placement/storage");
 }catch(Throwable t){t.printStackTrace();System.out.println("MTGCOMPANION_INTEGRATION_FAIL");}finally{server.halt(false);}});}
}
