package dev.casz.mtg;
import com.spider.mtgcard.client.compat.*;
import com.spider.mtgcard.util.TcgCardMeta;
import net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.input.MouseButtonEvent;
import net.minecraft.network.chat.Component;
import net.minecraft.core.BlockPos;
import net.minecraft.world.item.ItemStack;
import org.lwjgl.util.tinyfd.TinyFileDialogs;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
public final class BankScreen extends LegacyScreen {
 final BlockPos pos; final int kind; Wire.Reply data;EditBox search,quantity,oracle,stats;int x,y,w,h,scroll=0,selected=-1,page=0,face=0,mana=0;boolean commander=true,grid=false,artMode=false;int artPage=0;String artKey="",oracleQuery="",statsQuery="";String query="",localMessage="";long lastSend=0;
 BankScreen(Wire.Reply data){super(Component.literal(switch(data.kind()){case 0->"Community Land Catalogue";case 1->"Community Token Catalogue";case 2->"Community Card Collection";case 3->"Deck Builder";default->"Card Counters";}));pos=data.pos();kind=data.kind();this.data=data;}
 void update(Wire.Reply reply){boolean changed=kind<2&&artMode!=reply.report().equals("art");data=reply;if(kind<2)artMode=reply.report().equals("art");selected=-1;scroll=0;localMessage="";if(changed){rememberFilters();rebuildWidgets();}}
 @Override protected void init(){int preferredHeight=kind<3?520:380;if(applyAutoFitGuiScale(640,preferredHeight))return;w=Math.min(width-16,640);h=Math.min(height-16,preferredHeight);x=(width-w)/2;y=(height-h)/2;clearWidgets();
  if(kind<3){button(grid?"List view":"Grid view",x+w-110,y+6,98,()->{rememberFilters();grid=!grid;scroll=0;rebuildWidgets();});button(artMode?"Back to search":"Choose artwork",x+w-154,y+30,142,()->{if(artMode){page=0;rememberFilters();send("search",query,0);}else if(selected>=0&&selected<data.rows().size()){artKey=data.rows().get(selected).key();artPage=0;grid=true;rememberFilters();send("arts",artKey,0);rebuildWidgets();}else localMessage="Select a card first.";});search=addRenderableWidget(new EditBox(font,x+12,y+30,w-242,20,Component.literal("Search")));search.setMaxLength(200);search.setValue(query);search.setHint(Component.literal(kind==2?"Search stored names or types":"Card name or Scryfall query"));button("Search",x+w-224,y+30,64,()->{page=0;rememberFilters();send("search",query,page);});if(kind==2)button("Deposit held",x+w-154,y+30,142,()->send("deposit","",0));if(kind==0){String[] names={"All","White","Blue","Black","Red","Green","Colorless"};for(int i=0;i<7;i++){final int at=i;button((i==0?mana==0:(mana&(1<<(i-1)))!=0)?"["+names[i]+"]":names[i],x+12+i*86,y+58,80,()->{rememberFilters();mana=at==0?0:mana^(1<<(at-1));page=0;rebuildWidgets();send("search",query,0);});}}if(kind==1){oracle=addRenderableWidget(new EditBox(font,x+12,y+58,290,20,Component.literal("Oracle text (optional)")));oracle.setMaxLength(200);oracle.setValue(oracleQuery);oracle.setHint(Component.literal("Oracle text (optional)"));stats=addRenderableWidget(new EditBox(font,x+310,y+58,150,20,Component.literal("Power/toughness")));stats.setMaxLength(40);stats.setValue(statsQuery);stats.setHint(Component.literal("P/T: 1/1 (optional)"));}
   button("Previous",x+12,y+h-62,76,()->{rememberFilters();if(artMode){artPage=Math.max(0,artPage-1);send("arts",artKey,artPage);}else{page=Math.max(0,page-1);send("search",query,page);}});button("Next",x+94,y+h-62,60,()->{rememberFilters();if(artMode){artPage++;send("arts",artKey,artPage);}else{page++;send("search",query,page);}});quantity=addRenderableWidget(new EditBox(font,x+162,y+h-62,40,20,Component.literal("Quantity")));quantity.setValue("1");quantity.setMaxLength(2);button("Take selected",x+210,y+h-62,120,()->{if(selected>=0&&selected<data.rows().size())try{send("withdraw",data.rows().get(selected).key(),Integer.parseInt(quantity.getValue()));}catch(NumberFormatException e){localMessage="Enter a quantity from 1 to 64.";}});
  }else if(kind==3){button("Import .txt",x+12,y+32,98,this::chooseFile);button("Paste list",x+116,y+32,86,()->importText(minecraft.keyboardHandler.getClipboard()));button("Check cards",x+208,y+32,100,()->send("plan","",commander?2:0));button("Shopping list",x+314,y+32,118,this::export);
   button(commander?"First = commander: ON":"First = commander: OFF",x+12,y+h-62,186,()->{commander=!commander;rebuildWidgets();});button("Build complete",x+204,y+h-62,126,()->send("build","",commander?2:0));button("Build available",x+336,y+h-62,126,()->send("build","",(commander?2:0)|1));
  }else{search=addRenderableWidget(new EditBox(font,x+12,y+32,180,20,Component.literal("Counter name")));search.setMaxLength(48);search.setHint(Component.literal("+1/+1, loyalty, charge…"));quantity=addRenderableWidget(new EditBox(font,x+198,y+32,68,20,Component.literal("Counter total")));quantity.setMaxLength(7);quantity.setValue("1");button("Set total",x+272,y+32,82,()->{try{send("counter",search.getValue(),Integer.parseInt(quantity.getValue()));}catch(NumberFormatException e){localMessage="Enter a number from 0 to 1000000.";}});button("Remove",x+360,y+32,76,()->send("counter",search.getValue(),0));button("+1",x+12,y+h-62,60,()->adjust(1));button("−1",x+78,y+h-62,60,()->adjust(-1));}
  button("Flip preview",x+w-150,y+h-62,138,()->face++);button("Done",x+w-84,y+h-30,72,this::onClose);
 }
 void rememberFilters(){if(search!=null)query=search.getValue();if(oracle!=null)oracleQuery=oracle.getValue();if(stats!=null)statsQuery=stats.getValue();}
 void button(String label,int bx,int by,int bw,Runnable action){addRenderableWidget(Button.builder(Component.literal(label),b->action.run()).bounds(bx,by,bw,20).build());}
 void send(String action,String text,int amount){long now=System.currentTimeMillis();if(now-lastSend<180)return;lastSend=now;if(action.equals("search"))rememberFilters();ClientPlayNetworking.send(new Wire.Request(pos,action,text,amount,action.equals("search")?mana:0,kind==1?oracleQuery:"",kind==1?statsQuery:""));localMessage="Working…";}
 void adjust(int amount){if(selected<0||selected>=data.rows().size())return;var row=data.rows().get(selected);send("counter",row.key(),(int)Math.clamp(row.count()+amount,0,1000000));}
 void chooseFile(){try{String path=TinyFileDialogs.tinyfd_openFileDialog("Import MTG decklist",minecraft.gameDirectory.getAbsolutePath(),null,"Text decklist (*.txt)",false);if(path!=null)loadFile(Path.of(path));}catch(Exception e){localMessage="File picker unavailable. Drag a .txt file here or paste the list.";}}
 @Override public void onFilesDrop(List<Path> files){if(kind==3&&!files.isEmpty())loadFile(files.getFirst());}
 void loadFile(Path file){try{if(!file.getFileName().toString().toLowerCase(Locale.ROOT).endsWith(".txt")){localMessage="Choose a .txt file.";return;}if(Files.size(file)>24000){localMessage="Decklist must be at most 24 KB.";return;}importText(Files.readString(file,StandardCharsets.UTF_8));}catch(Exception e){localMessage="Could not read that file: "+e.getMessage();}}
 void importText(String text){if(text.length()>24000){localMessage="Decklist is too long.";return;}send("import",text,commander?2:0);}
 void export(){try{if(data.report().isBlank()){localMessage="No missing cards to export. Import/check a list first.";return;}Path dir=minecraft.gameDirectory.toPath().resolve("mtgcompanion/exports");Files.createDirectories(dir);Path path=dir.resolve("missing-cards-"+LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss-SSS"))+".txt");Files.writeString(path,data.report(),StandardCharsets.UTF_8,StandardOpenOption.CREATE_NEW);minecraft.keyboardHandler.setClipboard(data.report());localMessage="Copied for store; saved: mtgcompanion/exports/"+path.getFileName();}catch(Exception e){localMessage="Could not save missing list: "+e.getMessage();}}
 @Override public boolean isPauseScreen(){return false;}
 @Override public void onClose(){if(ClientPlayNetworking.canSend(Wire.Request.TYPE))ClientPlayNetworking.send(new Wire.Request(pos,"close","",0));super.onClose();}
 @Override public boolean mouseScrolled(double mx,double my,double dx,double dy){if(kind<3)scroll=CardBrowser.clampScroll(scroll-(int)Math.signum(dy)*(grid?4:3),data.rows().size(),w-206,h-listTop()-66,grid);else scroll=Math.clamp(scroll-(int)Math.signum(dy)*3,0,Math.max(0,data.rows().size()-visible()));return true;}
 int listTop(){return kind<2?120:92;}
 int visible(){return Math.max(1,(h-listTop()-66)/24);}
 @Override public boolean mouseClicked(MouseButtonEvent event,boolean doubleClick){int mx=(int)event.x(),my=(int)event.y();if(kind<3){int at=CardBrowser.hit(mx,my,x+12,y+listTop(),w-206,h-listTop()-66,scroll,data.rows().size(),grid);if(at>=0){selected=at;face=0;return true;}return super.mouseClicked(event,doubleClick);}if(mx>=x+12&&mx<x+w-194&&my>=y+listTop()&&my<y+listTop()+visible()*24){int at=scroll+(my-y-listTop())/24;if(at<data.rows().size()){selected=at;face=0;if(kind==4){search.setValue(data.rows().get(at).key());quantity.setValue(Long.toString(data.rows().get(at).count()));}return true;}}return super.mouseClicked(event,doubleClick);}
 @Override public void render(GuiGraphics g,int mx,int my,float delta){g.fill(0,0,width,height,0xC0080E18);g.fill(x,y,x+w,y+h,0xFF152032);g.drawString(font,title,x+12,y+12,0xFFFFFFFF);g.drawString(font,font.plainSubstrByWidth(data.message(),w-24),x+12,y+(kind<2?88:62),0xFFB3DFFF);
  String help=kind==3?"Databases: within 4 blocks · Output: empty deckbox touching builder":kind==4?"Click a counter to edit. Setting zero removes it.":"Click a card to select it · Scroll the list · Land/token copies are unlimited";g.drawString(font,font.plainSubstrByWidth(help,w-24),x+12,y+(kind<2?103:77),0xFF9CADC6);
  int listW=w-206;if(kind<3)CardBrowser.render(g,font,data.rows(),x+12,y+listTop(),listW,h-listTop()-66,scroll,selected,grid,artMode);else for(int i=0;i<visible();i++){int at=scroll+i;if(at>=data.rows().size())break;var row=data.rows().get(at);int ry=y+listTop()+i*24;g.fill(x+12,ry,x+12+listW,ry+22,at==selected?0xFF365880:0xFF22324B);String label=kind==3?(row.count()<0?"… ":row.count()>=row.requested()?"✓ ":row.count()>0?"◐ ":"✗ ")+row.key()+" ["+(row.count()<0?"?":row.count())+"/"+row.requested()+"]":kind==4?row.key()+" : "+row.count():TcgCardMeta.displayName(row.card())+"  ["+(row.count()<0?"∞":row.count())+"]";g.drawString(font,font.plainSubstrByWidth(label,listW-12),x+18,ry+7,kind==3?(row.count()>=row.requested()?0xFF90E8A0:row.count()>0?0xFFFFD37E:0xFFFF9E9E):0xFFFFFFFF);}
  ItemStack card=selected>=0&&selected<data.rows().size()?data.rows().get(selected).card():kind==4&&!data.rows().isEmpty()?data.rows().getFirst().card():ItemStack.EMPTY;if(!card.isEmpty())ClientCompanion.art(g,card,face%Math.max(1,TcgCardMeta.faceCount(card)),x+w-182,y+listTop(),170,h-listTop()-68);
  if(data.rows().isEmpty()&&kind==3){g.drawString(font,"Import .txt, drag a file here, or paste a decklist.",x+16,y+110,0xFFFFFFFF);if(!data.report().isBlank()){g.drawString(font,"Missing cards (export for your shopping list):",x+16,y+134,0xFFFFCC88);int ry=y+154;for(String line:data.report().split("\\R")){if(ry>y+h-86)break;g.drawString(font,font.plainSubstrByWidth(line,w-32),x+16,ry,0xFFFFDDAB);ry+=14;}}}
  if(!localMessage.isEmpty())g.drawString(font,font.plainSubstrByWidth(localMessage,w-112),x+12,y+h-23,0xFFFFDA8A);
  super.render(g,mx,my,delta);
 }
}